### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by chozelinek** [richardpaulhudson/holmes-extractor#15]
I'm working with a Macbook Pro, Intel, python 3.9.11, using MacOS Ventura. I've followed the instructions in the readme to install the dependencies. I'm just trying to run the first example in a python script like this:

```python
import holmes_extractor as holmes
manager = holmes.Manager("en_core_web_trf", number_of_workers=1)
manager.register_search_phrase('A big dog chases a cat')
manager.start_chatbot_mode_console()
```

I get the following traceback:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jose/workspace/dm_disclosure_extraction/disclosure_prototypes/holmes.py", line 3, in <module>
    manager = holmes.Manager("en_core_web_trf", number_of_workers=1)
  File "/Users/jose/.pyenv/versions/3.9.11/envs/experiments/lib/python3.9/site-packages/holmes_extractor/manager.py", line 271, in __init__
    self.multiprocessing_manager = MultiprocessingManager()
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/managers.py", line 554, in start
    self._process.start()
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/Users/jose/workspace/dm_disclosure_extraction/disclosure_prototypes/holmes.py", line 3, in <module>
    manager = holmes.Manager("en_core_web_trf", number_of_workers=1)
  File "/Users/jose/.pyenv/versions/3.9.11/envs/experiments/lib/python3.9/site-packages/holmes_extractor/manager.py", line 271, in __init__
    self.multiprocessing_manager = MultiprocessingManager()
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/managers.py", line 558, in start
    self._address = reader.recv()
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/Users/jose/.pyenv/versions/3.9.11/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError
```

**Comment by richardpaulhudson** [comment]
The advice in the stack trace refers to your script rather than to the library. I reproduced the problem on my own Mac and solved it by replacing your code with

```
 if __name__ == '__main__':
    import holmes_extractor as holmes
    manager = holmes.Manager("en_core_web_trf", number_of_workers=1)
    manager.register_search_phrase('A big dog chases a cat')
    manager.start_chatbot_mode_console()
```
